[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
extra_scripts = pre:version.py

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DUEC_CONTROLLER_URL=\"https://esp32-universal-controller.onrender.com\"
    -DARDUINO_LOOP_STACK_SIZE=16384
