[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DUEC_CONTROLLER_URL=\"https://esp32-universal-controller.onrender.com\"
    -DUEC_FIRMWARE_VERSION=\"0.1.0\"
    -DUEC_BUILD_ID=\"led-blink-central-test::0.1.0\"
